version: '3.1'
services:
  API:
    image: 'parking-control.jar'
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/parking-control-db
      - SPRING_DATASOURCE_USERNAME=emanuel
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  PostgreSQL:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=emanuel
      - POSTGRES_DB=parking-control-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U emanuel -d parking-control-db" ]
      interval: 10s
      timeout: 5s
      retries: 5

